---
- name: Create security group
  ec2_group:
    name: "{{ project_name }}_security_group"
    description: "{{ project_name }} security group"
    region: "{{ region }}"
    rules:
      - proto: tcp  # ssh
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp  # http
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp  # http
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp  # http
        from_port: 85
        to_port: 85
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: test_firewall

- debug: var=test_firewall

- name: Create an EC2 key
  ec2_key:
    name: "{{ project_name }}-{{ env }}-key"
    region: "{{ region }}"
  register: ec2_key

- debug: var=ec2_key

- name: debugging register
  debug: var=ec2_key.key.private_key


- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest="/home/ec2-user/ec2/aws-private.pem" mode=0600
  when: ec2_key.changed

- name: Create an EC2 instance
  ec2:
    key_name: "{{ project_name }}-{{ env }}-key"
    region: "{{ region }}"
    group_id: "{{ test_firewall.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    instance_tags:
        env: "{{ env }}"
    count_tag: env
    exact_count: 1
    vpc_subnet_id: subnet-0b8c11669c0699684
    assign_public_ip: yes
  register: ec2

- debug: var=ec2 

- name: Add the newly created EC2 instance(s) to host group
  lineinfile: 
    path: "{{ hostpath }}"
    regexp: "{{ item.public_ip }}"
    insertafter: "[webserver]"
    line: "{{ item.public_ip }}"
    state: present
  with_items: 
    - "{{ec2.instances}}"

- name: Wait for SSH to come up
  shell: cat /home/ec2-user/ec2/hosts

- include_role:
    name: my_role
  delegete_to: "{{ ec2.instances.public_ip }}"
  with_items:
    - "{{ec2.instances}}"
